---
swagger: "2.0" 
info:
  description: "Descricao da API de pagamento"
  version: "1.0.0"
  title: "Pagamento API"
  contact:
    email: "carlinstr@gmail.com"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: "localhost:8080"
basePath: "/api/v1"
schemes:
 - http    
tags: 
  - name: "Pagamento"
    description: "Acesso a operações de pagamento"

paths:
  /pagamento:
    get:
      tags: 
        - "Pagamento"
      operationId: "buscaPagamento"
      description: "|"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Pagamento"
          headers: {}
    
definitions:
  Pagamento:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "Id do pagamento."
      status:
        type: "string"
        description: "Status do pagamento"
      valor:
        type: "number"
        format: "double"
        description: "Valor do pagamento."